name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # OPTIONAL: clean install locally, just for faster error catching
      - name: Install Dependencies Locally (optional)
        run: npm install --legacy-peer-deps

      - name: Upload Project to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          source: "." # uploads the entire frontend folder
          target: "/var/www/leadnary/frontend"
          strip_components: 0

      - name: SSH into VPS & Build + Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /var/www/leadnary/frontend
            npm install --legacy-peer-deps
            npm run build
            pm2 restart leadnary-frontend || pm2 start npm --name "leadnary-frontend" -- start
